[book]
authors = ["Julián Rojas"]
language = "en"
multilingual = false
src = "src"
title = "Decentralised Linked Data architectures for the transport domain"

[build]
build-dir = "docs"

[preprocessor.bib]
bibliography = "bibliography/refs.bib"
title = "References"
hb-tpl = "bibliography/reference-template.hbs"
cite-hb-tpl = "bibliography/citation-template.hbs"

[output.html]
git-repository-url = "https://github.com/julianrojas87/phd-webbook"
additional-js = [
    "src/bibliography/load-citations.js",
    "src/bibliography/bibtex-parser.js"
]
